{
 "title": "Presearch Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_uptime_seconds" }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "total_number_of_requests" }
   ]
  },
  {
   "title": "Total Pre Earned",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_pre_earned" }
   ]
  },
  {
   "title": "Number of disconnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "total_number_of_disconnections" }
   ]
  },
  {
   "title": "average_latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "average_latency_ms" }
   ]
  },
  {
   "title": "Uptime Percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_uptime_percentage" }
   ]
  },
  {
   "title": "Avg Uptime Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "average_uptime_score" }
   ]
  }
 ]
}