scrape_configs:
  - job_name: 'presearch'
    scrape_interval: 10s
    static_configs:
      - targets: ['URL_ESCAPED_NODE_KEY']
    metrics_path: /probe
    relabel_configs:
      - target_label: __address__
        replacement: localhost:8082
